"""
email_service.py - Sends CoA reports via SMTP email
"""
import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from pathlib import Path
from typing import Optional

from config import load_smtp_config

# --- Email Config (loaded from smtp_config.json) ---
cfg = load_smtp_config()
SMTP_HOST = cfg.get("smtp_host", "smtp.gmail.com")
SMTP_PORT = cfg.get("smtp_port", 587)
SMTP_USERNAME = cfg.get("smtp_username", "")
SMTP_PASSWORD = cfg.get("smtp_password", "")
SMTP_FROM_NAME = cfg.get("smtp_from_name", "CoAutomate System")
SMTP_FROM_EMAIL = SMTP_USERNAME


def send_coa_email(
    recipient_email: str,
    recipient_name: str,
    period_label: str,
    month_name: str,
    year: int,
    attachment_path: Path,
) -> bool:
    """
    Sends a CoA report email with the Excel file as an attachment.

    Returns True on success, False on failure.
    """
    if not SMTP_USERNAME or not SMTP_PASSWORD:
        print("[EMAIL] SMTP not configured. Skipping email send.")
        return False

    try:
        msg = MIMEMultipart()
        msg["From"] = f"{SMTP_FROM_NAME} <{SMTP_FROM_EMAIL}>"
        msg["To"] = recipient_email
        msg["Subject"] = (
            f"Certificate of Attendance – {month_name} {year} "
            f"(Period {period_label})"
        )

        body = f"""Dear {recipient_name},

Please find attached your Certificate of Attendance (CoA) for the period 
{period_label} of {month_name} {year}.

This report has been automatically generated by CoAutomate. 
Please review it and submit it accordingly.

Best regards,
CoAutomate Automated System
"""
        msg.attach(MIMEText(body, "plain"))

        # Attach the Excel file
        with open(str(attachment_path), "rb") as f:
            part = MIMEBase("application", "vnd.openxmlformats-officedocument.spreadsheetml.sheet")
            part.set_payload(f.read())
            encoders.encode_base64(part)
            part.add_header(
                "Content-Disposition",
                f'attachment; filename="{attachment_path.name}"',
            )
            msg.attach(part)

        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(SMTP_USERNAME, SMTP_PASSWORD)
            server.sendmail(SMTP_FROM_EMAIL, recipient_email, msg.as_string())

        print(f"[EMAIL] Sent CoA to {recipient_email}")
        return True

    except Exception as e:
        print(f"[EMAIL] Failed to send to {recipient_email}: {e}")
        return False
